server:
  port: ${PORT_NUMBER}
#  tomcat:
#    additional-tld-skip-patterns: "*.jar"


logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  messages:
    basename: messages
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/admin/*.xml, classpath:mapper/user/*.xml
  type-aliases-package: com.unibus.admin.domain, com.unibus.admin.dto, com.unibus.user.domain, com.unibus.user.dto